Adicionando desafio Aplicação de Console de Carteria de Investimentos
stone-payments/credit-tech-challenges pull request #1
Opened 2021-04-20 16:48 UTC by joaopmjm

2021-04-20 17:41 UTC, gabrielclima requested changes

2021-04-20 17:41 UTC, gabrielclima commented on README.md
> +  -  [/Aplicacao-de-Console-de-Carteira-de-Investimentos/README.md](https://github.com/stone-payments/credit-tech-challenges/Aplicacao-de-Console-de-Carteira-de-Investimentos/README.md).
```suggestion
  -  [Aplicacao de Console - Carteira de Investimentos](https://github.com/stone-payments/credit-tech-challenges/Aplicacao-de-Console-de-Carteira-de-Investimentos/README.md).
```

Acha que fica melhor assim?

2021-04-20 17:44 UTC, afelipems commented
será que não rola chamar os markdown dos desafios de DESCRIPTION.md e deixar README.md só no readme do projeto mesmo?

2021-04-20 17:45 UTC, gabrielclima commented on README.md
> +  -  [Aplicacao de Console - Carteira de Investimentos](https://github.com/stone-payments/credit-tech-challenges/Aplicacao-de-Console-de-Carteira-de-Investimentos/README.md).
```suggestion
- [Aplicacao de Console - Carteira de Investimentos](https://github.com/stone-payments/credit-tech-challenges/Aplicacao-de-Console-de-Carteira-de-Investimentos/README.md)
```

2021-04-20 17:45 UTC, joaopmjm commented
> será que não rola chamar os markdown dos desafios de DESCRIPTION.md e deixar README.md só no readme do projeto mesmo?

acho melhor, mais intuitivo talvez, deixar o README na raiz, e em cada desafio ter o DESCRIPTION

2021-04-20 17:46 UTC, afelipems commented
@joaopmjm enriquece a description por favor. O que é o repositório? Para que ele serve? Quem são os responsáveis por esse repositório contato)? Por aí vai.

2021-04-20 17:49 UTC, joaopmjm commented
> @joaopmjm enriquece a description por favor. O que é o repositório? Para que ele serve? Quem são os responsáveis por esse repositório contato)? Por aí vai.

Vou colocar os contatos de quem ta pra ser notificado no basecamp

2021-04-21 14:33 UTC, afelipems approved these changes

2021-04-21 14:47 UTC, gabrielclima requested changes
Tem que ajeitar o link pro desafio. Tá dando 404

2021-04-21 15:20 UTC, afelipems approved these changes

2021-04-21 15:20 UTC, afelipems approved these changes

2021-04-21 19:35 UTC, gabrielclima approved these changes
LGTM

2021-04-21 19:36 UTC, merged