Adicionando desafio API de Contracheques
stone-payments/credit-tech-challenges pull request #2
Opened 2021-04-20 17:31 UTC by joaopmjm

2021-04-20 17:40 UTC, gabrielclima requested changes

2021-04-20 17:40 UTC, gabrielclima commented on README.md
> +  - [/API-de-Contracheque/README.md](https://github.com/stone-payments/credit-tech-challenges/API-de-Contracheque/README.md).
```suggestion
  - [API de Contracheque](https://github.com/stone-payments/credit-tech-challenges/API-de-Contracheque/README.md).
```

Acho que fica melhor a leitura assim. O que acha?

2021-04-20 17:44 UTC, gabrielclima commented on README.md
> +  - [API de Contracheque](https://github.com/stone-payments/credit-tech-challenges/API-de-Contracheque/README.md).
```suggestion
- [API de Contracheque](https://github.com/stone-payments/credit-tech-challenges/API-de-Contracheque/README.md)
```

2021-04-21 14:05 UTC, afelipems commented on API-de-Contracheque/DESCRIPTION.md
> +        |Acima de 4.664,68|27,5|869,36|
![image](https://user-images.githubusercontent.com/35966596/115567191-5e3dd400-a291-11eb-90b3-739057a59046.png)

Essa tabela ficou muito complicada de ler, pode inserir imagem que nem tá no documento

2021-04-21 14:05 UTC, afelipems commented
Como fica esse markdown? Cadê print? Qual desafio está sendo importado? Como vou saber se está correto?

2021-04-21 14:06 UTC, afelipems commented
usa a description a seu favor para responder essas perguntas.

https://github.com/stone-payments/credit-tech-challenges/pull/2#issuecomment-824089242

2021-04-21 14:22 UTC, joaopmjm reviewed
Description Updated

2021-04-21 14:22 UTC, joaopmjm commented on API-de-Contracheque/DESCRIPTION.md
> +        |Acima de 4.664,68|27,5|869,36|
No preview que o Visual Studio da pro MarkDown a tabela realmente vira uma tabela parecendo de Word, não fica feio assim. Mas posso colocar uma imagem sim

2021-04-21 14:33 UTC, afelipems approved these changes

2021-04-21 14:42 UTC, gabrielclima commented
![image](https://user-images.githubusercontent.com/8717587/115572786-9b589500-a296-11eb-8dd0-c2580275b4ad.png)
O link tá direcionando pra um caminho que não existe

2021-04-21 14:44 UTC, gabrielclima commented
O link deveria ser esse: https://github.com/stone-payments/credit-tech-challenges/blob/Add/Challenge-API-de-contracheques/API-de-Contracheque/DESCRIPTION.md

2021-04-21 14:45 UTC, gabrielclima requested changes
Só falta acertar o readme da description

2021-04-21 14:46 UTC, joaopmjm commented
> O link deveria ser esse: https://github.com/stone-payments/credit-tech-challenges/blob/Add/Challenge-API-de-contracheques/API-de-Contracheque/DESCRIPTION.md

O link no README só vai funcionar quando o PR adicionando o challenge for mergeado, mas pelo que eu entendi eh que cada desafio vai estar em uma branch separada?

2021-04-21 14:54 UTC, gabrielclima commented
> O link no README só vai funcionar quando o PR adicionando o challenge for mergeado, mas pelo que eu entendi eh que cada desafio vai estar em uma branch separada?

Acredito que funciona mesmo estando na branch. mas pelo que eu entendi eh que cada desafio vai estar em uma branch separada?

> mas pelo que eu entendi eh que cada desafio vai estar em uma branch separada?

não... a ideia é tudo ir pra master mesmo

2021-04-21 19:35 UTC, gabrielclima submitted a review, later dismissed
LGTM

2021-04-21 19:42 UTC, gabrielclima approved these changes

2021-04-21 19:43 UTC, afelipems approved these changes

2021-04-21 19:43 UTC, merged

2021-04-21 19:43 UTC, gabrielclima approved these changes